name: Build Xamarin.Android app

on:

  workflow_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    

    - name: Setup .NET Core SDK 5.0.x
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '5.0.x'

    - name: Install dependencies
      run: nuget restore ./ValmontApp.Mobile/ValmontApp.Mobile.sln

    - name: Build
      run: msbuild ./ValmontApp.Mobile/ValmontApp.Mobile/ValmontApp.Mobile.Android/ValmontApp.Mobile.Android.csproj /t:PackageForAndroid /p:Configuration=Release
 
   
